[workspace]
members = ["tests"]

[workspace.package]
version = "0.9.0"
authors = [
  "Martin Haug <mhaug@live.de>",
  "Laurenz Stampfl <laurenz.stampfl@gmail.com>",
]
edition = "2021"
repository = "https://github.com/typst/svg2pdf"
readme = "README.md"
license = "MIT OR Apache-2.0"

[package]
name = "svg2pdf"
description = "Convert SVG files to PDFs."
categories = ["encoding", "graphics", "multimedia"]
keywords = ["svg", "pdf", "vector-graphics", "conversion"]
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[features]
default = ["image"]
image = ["dep:image"]
cli = ["dep:clap", "dep:termcolor", "usvg/text", "dep:fontdb"]

[lib]
test = false
doctest = false

[[bin]]
name = "svg2pdf"
path = "src/main.rs"
required-features = ["cli"]

[build-dependencies]
clap = { version = "4.4.2", features = ["derive", "string"] }
clap_complete = "4.4.3"
clap_mangen = "0.2.14"

[dependencies]
miniz_oxide = "0.7"
pdf-writer = "0.9"
usvg = { version = "0.36", default-features = false }
image = { version = "0.24", default-features = false, features = [
  "jpeg",
  "png",
  "gif",
], optional = true }
termcolor = { version = "1", optional = true }
clap = { version = "4.4.2", features = ["derive"], optional = true }
fontdb = { version = "0.15", optional = true }

[dev-dependencies]
usvg = { version = "0.36.0" }
